default: &default
  adapter: postgresql
  encoding: unicode
  host: dbp
  username: oveja
  password: oveja
  pool: 5

development:
  <<: *default
  database: linksApi_dev
  username: oveja
  password: oveja

test:
  <<: *default
  database: linksApi_test
  username: oveja
  password: oveja

production:
  <<: *default
  database: linksApi_prod
  username: oveja
  password: <%= ENV['dbpassword'] %>
