default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: oveja123

development:
  <<: *default
  database: linksApi_dev
  username: postgres
  password: oveja123

test:
  <<: *default
  database: linksApi_test
  username: postgres
  password: oveja123

production:
  <<: *default
  database: linksApi_prod
  username: oveja
  password: <%= ENV['dbpassword'] %>
